version: 2.0.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU

skip_tags: true
skip_branch_with_pr: true

cache:
  - packages -> **\packages.config
  - OpenCover -> appveyor.yml
  - ReportGenerator -> appveyor.yml
  - coverage-history -> appveyor.yml

environment:
  PFX_PASSWORD:
    secure: wB19redOwiER/t000/oJpCZEu41oxfSlcBuVUNaILO0=

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)

install:
- cmd: dotnet restore
- cmd: nuget install -ExcludeVersion OpenCover
- cmd: nuget install -ExcludeVersion ReportGenerator

build_script:
- ps: Import-PfxCertificate -FilePath EliteLogAgent\code-signing.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $(ConvertTo-SecureString "$env:PFX_PASSWORD" -AsPlainText -Force)
- msbuild EliteLogAgent\EliteLogAgent.csproj /verbosity:minimal /t:Publish /p:PublishProfile=EliteLogAgent\Properties\PublishProfiles\ClickOnceProfile.pubxml /p:ApplicationVersion=%APPVEYOR_BUILD_VERSION% /p:MinimumRequiredVersion=%APPVEYOR_BUILD_VERSION%

test_script:
- dotnet test --configuration Release --test-adapter-path:. --logger:Appveyor

artifacts:
- path: EliteLogAgent\bin\Any CPU\Release\net5.0-windows\app.publish\
  name: ClickOnce

for:
- branches:
    only: 
    - prod
  deploy:
  - provider: AzureBlob
    artifact: Clickonce
    storage_account_name: elitelogagent
    container: clickonce
    unzip: true
    storage_access_key:
      secure: QG+FUaRxa8VX+7XDNhCX/XLHv+G/2PyACt8POHWNVOKm9jgT4/1WCYNfsTHdsXMrZyDh77uDw68ulHtz7i/AREoNxu1y9Z5ZD+nrDL6/R8TwCDljhq9S+EUusNk3CCMZ
  - provider: GitHub
    tag: release/$(appveyor_build_version)
    release: $(appveyor_build_version)
    auth_token:
      secure: 7uCw0Z3VgTACacpcn/VbD5PsLzez8JKRBjdt2nI2fTVgkU4E7EzIX0xRPhhktZDe
    artifact: Portable
    draft: false
    prerelease: false
    force_update: true
